### ISSUE TITLE
OOP2 chat applicatie

### ISSUE THREAD

**Issue by henkmollema** [henkmollema/NHL#5]
- [x] Admin client C++
- [x] Censor client C++
- [x] Basic Java client
- [x] Censor client Java
- [x] Client C++
- [x] Direct bericht van censor naar admin via server (`!admin`)
- [x] Mute-command van admin naar server om gebruiker te muten (`!mute:<user>`)
- [x] Gebruiker muten voor 10s
- [x] Commando's niet tonen in chat venster (`!admin` en `!mute`)

**Comment by Lg0enga** [comment]
:+1: Grote klasse @henkmollema. Waar is mijn chat gebleven :cold_sweat:
